# - Try to find mpris-qt5
# Once done, this will define
#
#  MPRISQT_FOUND - system has DBus
#  MPRISQT_INCLUDE_DIRS - the DBus include directories
#  MPRISQT_LIBRARIES - link these to use DBus

FIND_PACKAGE(PkgConfig)
PKG_CHECK_MODULES(PC_MPRISQT QUIET mpris-qt5)

FIND_LIBRARY(MPRISQT_LIBRARIES
    NAMES mpris-qt5
    HINTS ${PC_MPRISQT_LIBDIR}
          ${PC_MPRISQT_LIBRARY_DIRS}
)

FIND_PATH(MPRIS_INCLUDE_DIR
    NAMES MprisQt/mpris.h
    HINTS ${PC_MPRISQT_INCLUDEDIR}
          ${PC_MPRISQT_INCLUDE_DIRS}
)

GET_FILENAME_COMPONENT(_MPRISQT_LIBRARY_DIR ${MPRISQT_LIBRARIES} PATH)
FIND_PATH(MPRISQT_INCLUDE_DIR
    NAMES MprisQt/mprisqt.h
    HINTS ${PC_MPRISQT_INCLUDEDIR}
	  ${PC_MPRISQT_INCLUDE_DIRS}
          ${_MPRISQT_LIBRARY_DIR}
          ${MPRISQT_INCLUDE_DIR}
    PATH_SUFFIXES include
)

SET(MPRISQT_INCLUDE_DIRS ${MPRISQT_INCLUDE_DIR} ${MPRIS_INCLUDE_DIR})

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(MprisQt REQUIRED_VARS MPRISQT_INCLUDE_DIRS MPRISQT_LIBRARIES)
